# Change these first
owner: openbb-finance # Your GitHub organization or username, where this repository lives
repo: uptime # The name of this repository

sites:
  - name: OpenBB.co
    url: https://openbb.co
  - name: OpenBB Terminal Docs
    url: https://docs.openbb.co/
  - name: Bot Platform
    url: $PAYMENTS_BACKEND_URL
  - name: OpenBB Pro
    url: $OPENBB_PRO_URL
  - name: Pro Backend
    url: $OPENBB_BACKEND_URL
  - name: AI Backend
    url: $OPENBB_AI_URL

status-website:
  # Add your custom domain name, or remove the `cname` line if you don't have a domain
  # Uncomment the `baseUrl` line if you don't have a custom domain and add your repo name there
  #cname: demo.upptime.js.org
  themeUrl: https://cdn.statically.io/gh/openbb-finance/uptime/master/assets/custom-theme.css
  baseUrl: /uptime
  logoUrl: https://cdn.statically.io/gh/openbb-finance/uptime/master/assets/logo.png
  name: OpenBB
  introTitle: "**OpenBB** is a leading open source investment analysis company. Our mission is to make investment research effective, powerful and accessible to everyone."
  introMessage: "Bot platform are dependent on Discord and Telegram status, if something is not working related to the bot verify [telegram status](https://downdetector.com/status/telegram/) and [discord status](https://discordstatus.com/)."
  favicon: https://openbb.co/favicons/favicon-32x32.png
  navbar:
    - title: Status
      href: /
    - title: GitHub
      href: https://github.com/OpenBB-finance/OpenBBTerminal
# Upptime also supports notifications, assigning issues, and more
# See https://upptime.js.org/docs/configuration
